on:push
jobs:
    runs-on:ubuntu-latest
    steps:
        -name:print triggered event
        run:echo "this job trigged when ${{github.event_name}}"
        -name:print os runner
        run:echo "this run on ${{runner.os}} server"
